### ISSUE TITLE
输入请求参数的面板跟随IDEA主题色调

### ISSUE THREAD

**Issue by Freedomisgood** [auto-generated/RestfulToolkit-fix#1]
是否能根据IDEA主题自动修改呢？ 灰暗的突出了一片白还挺突兀

**Comment by code142857** [comment]
改成黑色主题显示黑色了
<img width="609" alt="image" src="https://user-images.githubusercontent.com/32949827/203535770-2a1e0b59-7509-42a6-911f-96554e2484b9.png">

**Comment by Freedomisgood** [comment]
好的谢谢~
